version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8085:8081"  # Maps localhost:8085 to container's port 8081
    volumes:
      - nexus-data:/nexus-data
    restart: always

volumes:
  nexus-data: