name: Publish to Maven Central

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate settings.xml
        uses: s4u/maven-settings-action@v2
        with:
          servers: |
            [
              {
                "id": "central",
                "username": "${{ secrets.CENTRAL_USERNAME }}",
                "password": "${{ secrets.CENTRAL_PASSWORD }}"
              }
            ]

      - name: Import and trust GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode > private.key
          gpg --batch --import private.key

          # Extract the full fingerprint (not just the key ID)
          KEY_FP=$(gpg --list-secret-keys --with-colons | grep '^fpr' | head -n1 | cut -d: -f10)
          echo "KEY_FP=$KEY_FP" >> $GITHUB_ENV

          # Set trust level to ultimate (6)
          echo "$KEY_FP:6:" | gpg --import-ownertrust
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set GPG_TTY
        run: echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Test GPG signing works
        run: echo "test" | gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --clearsign
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy to Maven Central
        run: mvn clean deploy -P central
      
      - name: Close Staging Repository
        run: |
          REPO_ID=$(curl -u "${{ secrets.CENTRAL_USERNAME }}:${{ secrets.CENTRAL_PASSWORD }}" \
            -H "Accept: application/json" \
            "https://oss.sonatype.org/service/local/staging/profile_repositories" | jq -r '.data[] | select(.type == "open") | .repositoryId')

          if [ -z "$REPO_ID" ]; then
            echo "No open staging repository found."
            exit 1
          fi

          curl -u "${{ secrets.CENTRAL_USERNAME }}:${{ secrets.CENTRAL_PASSWORD }}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{\"data\": {\"stagedRepositoryId\": \"$REPO_ID\", \"description\": \"Close $REPO_ID\"}}" \
            "https://oss.sonatype.org/service/local/staging/profiles/${{ secrets.SONATYPE_PROFILE_ID }}/finish"

      - name: Release Staging Repository
        run: |
          REPO_ID=$(curl -u "${{ secrets.CENTRAL_USERNAME }}:${{ secrets.CENTRAL_PASSWORD }}" \
            -H "Accept: application/json" \
            "https://oss.sonatype.org/service/local/staging/profile_repositories" | jq -r '.data[] | select(.type == "closed") | .repositoryId')

          if [ -z "$REPO_ID" ]; then
            echo "No closed staging repository found."
            exit 1
          fi

          curl -u "${{ secrets.CENTRAL_USERNAME }}:${{ secrets.CENTRAL_PASSWORD }}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{\"data\": {\"stagedRepositoryId\": \"$REPO_ID\", \"description\": \"Release $REPO_ID\"}}" \
            "https://oss.sonatype.org/service/local/staging/profiles/${{ secrets.SONATYPE_PROFILE_ID }}/promote"
