name: Publish to Maven Central and GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate settings.xml
        uses: s4u/maven-settings-action@v2
        with:
          servers: |
            [
              {
                "id": "central",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_PASSWORD }}"
              },
              {
                "id": "github",
                "username": "${{ secrets.GITHUB_ACTOR }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Deploy to Maven Central
        run: mvn clean deploy -P central -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy to GitHub Packages
        run: mvn deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}