name: Publish to Maven Central

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate settings.xml
        uses: s4u/maven-settings-action@v2
        with:
          servers: |
            [
              {
                "id": "central",
                "username": "${{ secrets.CENTRAL_USERNAME }}",
                "password": "${{ secrets.CENTRAL_PASSWORD }}"
              }
            ]

      - name: Import and trust GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode > private.key
          gpg --batch --import private.key

          KEY_ID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d: -f5)
          echo "KEY_ID=$KEY_ID" >> $GITHUB_ENV

          echo "$KEY_ID:6:" | gpg --import-ownertrust
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set GPG_TTY
        run: echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Test GPG signing works
        run: echo "test" | gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --clearsign
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy to Maven Central
        run: mvn clean deploy -P central